[package]
name = "CodeAbbey_17"
version = "0.1.0"
authors = ["Brighton Sikarskie <brighton.sikarskie@tuta.io>"]
homepage = "https://www.codeabbey.com/index/task_view/array-checksum"
license = "MIT"
edition = "2018"

[dependencies]
