[package]
name = "CodeAbbey_21"
version = "0.1.0"
authors = ["Brighton Sikarskie <brighton.sikarskie@tuta.io>"]
edition = "2018"
homepage = "https://www.codeabbey.com/index/task_view/array-counters"
license = "MIT"
edition = "2018"

[dependencies]
