[package]
name = "CodeAbbey_30"
version = "0.1.0"
authors = ["Brighton Sikarskie <bsikar@tuta.io>"]
homepage = "https://www.codeabbey.com/index/task_view/reverse-string"
license = "MIT"
edition = "2018"

[dependencies]
