[package]
name = "code_abbey_16"
version = "0.1.0"
authors = ["Brighton Sikarskie <brighton.sikarskie@tuta.io>"]
homepage = "https://www.codeabbey.com/index/task_view/average-of-array"
license = "MIT"
edition = "2018"

[dependencies]
