[package]
name = "CodeAbbey_13"
version = "0.1.0"
authors = ["Brighton Sikarskie <bsikar@tuta.io>"]
homepage = "https://www.codeabbey.com/index/task_view/weighted-sum-of-digits"
license = "MIT"
edition = "2018"

[dependencies]
