[package]
name = "CodeAbbey_41"
version = "0.1.0"
authors = ["Brighton Sikarskie <brighton.sikarskie@tuta.io>"]
homepage = "https://www.codeabbey.com/index/task_view/median-of-three"
license = "MIT"
edition = "2018"

[dependencies]
